name: mpst
version: 0.1.0.0
synopsis: Multiparty session types experiments
category: Concurrency
license: BSD-3-Clause
author: Kai Pischke
maintainer: Kai Pischke
extra-source-files:
  - README.md

dependencies:
  - base >= 4.14 && < 5
  - containers
  - deepseq
  - megaparsec
  - parser-combinators
  - prettyprinter
  - transformers
  - mtl
  - array
  - graphviz
  - text
  - process
  - temporary
  - time

library:
  source-dirs: src
  exposed-modules:
    - MPST
    - Syntax
    - Automata
    - Balanced
    - DeadlockFreedom
    - Merge
    - MpstkBackend
    - Project
    - Safety
    - Subtyping
    - Synthesise
    - Typecheck
    - Infer
    - Liveness
    - Visualise
    - Benchmark.Catalogue
    - Benchmark.Generators
    - Benchmark.Size
    - Benchmark.Runner
    - Benchmark.LaTeX
    - Benchmark.Types
    - Benchmark.QBF
  other-modules:
    - Syntax.AST
    - Syntax.AlphaEq
    - Syntax.Parser
    - Syntax.Pretty
    - Syntax.WellFormed

executables:
  mpst-app:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mpst

  mpst-bench:
    main: Main.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mpst
      - async
      - process
      - time

tests:
  mpst-test:
    main: Spec.hs
    source-dirs: test
    other-modules:
      - AutomataReconstructionSpec
      - BalancedSpec
      - ContextRandomSpec
      - DeadlockFreedomSpec
      - Fig4VennSpec
      - LessIsMoreSpec
      - MergeSpec
      - MpstkBackendSpec
      - ProcessSpec
      - QBFSpec
      - ProjectionSpec
      - SafetySpec
      - SubtypingSpec
      - SynthesiseSpec
      - TypecheckSpec
      - InferSpec
      - LivenessSpec
      - RoundtripSpec
      - TestGenerators
      - WellFormedSpec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - mpst
      - QuickCheck
      - hspec
